{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "antimetal-agent.fullname" . }}-rolebinding
  labels:
    {{- include "antimetal-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "antimetal-agent.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "antimetal-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
