apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "antimetal-agent.fullname" . }}
  labels:
    {{- include "antimetal-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "antimetal-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "antimetal-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "antimetal-agent.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /agent
          args:
            - --leader-elect
            {{- with .Values.logLevel }}
            - --zap-log-level={{ . }}
            {{- end }}
            {{- with .Values.apiAddress }}
            - --intake-address={{ . }}
            {{- end }}
            - --intake-api-key=$(API_KEY)
            - --kubernetes-provider={{ required "Must set provider.name" .Values.provider.name }}
            {{- $providerData := get .Values.provider .Values.provider.name }}
            {{- range  $key, $value := $providerData }}
            - --kubernetes-provider-{{ $.Values.provider.name }}-{{ $key }}={{ $value }}
            {{- end }}
            {{- if .Values.performance.enable }}
            - --enable-performance-collectors
            {{- end }}
            {{- if .Values.performance.exporters.otel.enable }}
            - --enable-otel
            {{- end }}
            {{- if .Values.metrics.enable }}
            - --metrics-bind-address={{ include "antimetal-agent.metricsServerPort" . | printf ":%s" }}
            - --metrics-secure={{ default false .Values.metrics.secure }}
            {{- if and .Values.metrics.secure .Values.metrics.tls }}
            - --metrics-cert-dir=/etc/antimetal-agent/tls
            - --metrics-cert-name=tls.crt
            - --metrics-key-name=tls.key
            {{- end }}
            {{- else }}
            - --metrics-bind-address=0
            {{- end }}
            {{- if .Values.pprof.enable }}
            - --pprof-address={{ printf ":%s" .Values.pprof.port }}
            {{- end }}
            - --data-directory
            - ''
          env:
            - name: KUBERNETES_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_PROC
              value: /host/proc
            - name: HOST_SYS
              value: /host/sys
            - name: HOST_DEV
              value: /host/dev
            - name: HOST_ETC
              value: /host/etc
            - name: HOST_VAR
              value: /host/var
            - name: HOST_CGROUP
              value: /host/cgroup
            {{- range .Values.extraEnvs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "antimetal-agent.apiKeySecretName" . }}
            {{- with .Values.extraEnvsFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: health
              containerPort: 8081
            {{- if .Values.metrics.enable }}
            - name: metrics
              containerPort: {{ include "antimetal-agent.metricsServerPort" . | int }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/antimetal
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: dev
              mountPath: /host/dev
              readOnly: true
            - name: machine-id
              mountPath: /host/etc/machine-id
              readOnly: true
            - name: dbus
              mountPath: /host/var/lib/dbus
              readOnly: true
            - name: cgroup
              mountPath: /host/cgroup
              readOnly: true
            {{- if and .Values.metrics.enable .Values.metrics.secure }}
            {{- with required "metrics.tls must be set" .Values.metrics.tls }}
            - name: metrics-tls
              mountPath: /etc/antimetal-agent/tls
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: machine-id
          hostPath:
            path: /etc/machine-id
        - name: dbus
          hostPath:
            path: /var/lib/dbus
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        {{- if and .Values.metrics.enable .Values.metrics.secure }}
        {{- with required "metrics.tls must be set" .Values.metrics.tls }}
        - name: metrics-tls
          secret:
            secretName: {{ required "metrics.tls.secretRef must be set" .secretRef }}
        {{- end }}
        {{- end }}
        {{- with .Values.extravolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
