{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "antimetal-agent.apiKeySecretName" . }}
  labels:
    {{- include "antimetal-agent.labels" . | nindent 4 }}
data:
  API_KEY: {{ .Values.apiKey | b64enc | quote }}
{{- end }}
