name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_release:
        type: boolean
        description: 'Force release even if no version bump detected'
        required: false
        default: false

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Chart Version Bumps
        shell: bash
        id: version_bump
        run: |
          # Diff HEAD against pre-merge state and look for version bump
          if git diff $(git rev-parse HEAD^1)..HEAD charts/*/Chart.yaml | grep -E '^\+version:'; then
            echo "is_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_bump=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.version_bump.outputs.is_bump == 'true' || inputs.force_release
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        if: steps.version_bump.outputs.is_bump == 'true' || inputs.force_release
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
